name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: setting variables from secrets
      run: |
        KEY_LABEL=${{ secrets.api_key_label }}
        KEY=${{ secrets.api_key_value }}
    - name: print secrets
      run: |
        echo ${KEY_LABEL} ${KEY}
