name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: setting variables from secrets
      env:
        KEY_LABEL: ${{ secrets.api_key_label }}
        KEY: ${{ secrets.api_key_value }}
        WORD: word
      run: |
        echo https://www.googleapis.com/youtube/v3/search?key=${env:KEY}&part=snippet,id&order=date&maxResults=1
        echo ${env:KEY_LABEL} ${env:KEY}
    - name: Decrypt large secret
      run: |
        chmod +x ./decrypt_secret.sh
        ./decrypt_secret.sh
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
    # This command is just an example to show your secret being printed
    # Ensure you remove any print statements of your secrets. GitHub does
    # not hide secrets that use this workaround.
    - name: Test printing your secret (Remove this step in production)
      run: cat $HOME/secrets/my_secret.json
